prometheus:
  config:
    scrape_configs:
      - job_name: node-scoped-example
        scrape_interval: 30s
        kubernetes_sd_configs:
        - role: pod
          selectors:
            - field: spec.nodeName=${KUBE_NODE_NAME}
              role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          regex: "true"
          action: keep
        - source_labels : [__meta_kubernetes_pod_label_app_kubernetes_io_name,__meta_kubernetes_pod_container_port_number]
          action: keep
          regex: prometheus-example-app;8080
        - action: replace
          target_label: job_label
          replacement: name-scoped-example